markdown : maruku
pygments : true
description : Tyler Hall is a three year Yahoo! veteran now doing Mac and iOS development full-time in Nashville. He's the author of VirtualHostX, Incoming!, Nottingham, and the Simple PHP Framework.
cdn_url : http://cdn.clickontyler.com
